# action.yml
name: "Wait on check"
author: "progapandist"
description: "Wait on a certain check to pass for commit"
inputs:
  ref:
    description: "A git ref to be checked: branch/tag/commit sha"
    required: true
  check-name:
    description: "A name of a check that has to pass"
    required: false
    default: ""
  check-regexp:
    description: "A regexp to match with the checks that have to pass"
    required: false
    default: ""
  repo-token:
    description: "A GitHub token for the repo"
    required: false
    default: ""
  wait-interval:
    description: "Seconds to wait between Checks API requests"
    required: false
    default: "10"
  running-workflow-name:
    description: "Name of the workflow to be ignored (the one who is waiting for the rest)"
    required: false
    default: ""
   timeout-minutes:
    description: "Minutes it should wait before timeout. It will run on timeout error if job's timeout-minutes is reached first."
    required: false
    default: "30"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.ref }}
    - ${{ inputs.check-name }}
    - ${{ inputs.check-regexp }}
    - ${{ inputs.repo-token }}
    - ${{ inputs.wait-interval }}
    - ${{ inputs.running-workflow-name }}
    - ${{ inputs.timeout-minutes }}
branding:
  icon: "check-circle"
  color: "green"
