name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_READ_ONLY_GITHUB_TOKEN }}

      # Runs a single command using the runners shell
      - name: Trigger wait_omitting-check-name workflow
        run: |
          random_num=$((RANDOM))
          chmod +x ./.github/trigger-scripts/push-tag-trigger.sh
          ./.github/trigger-scripts/push-tag-trigger.sh "test-omitting-check-name/v" $random_num
