name: Simple Task

on:
  push:
    branches:
  workflow_dispatch:
    inputs:
      delay_seconds:
        description: 'Time to delay'
        required: false
        default: 2

jobs:
  simple-task:
    runs-on: ubuntu-latest

    steps:
      - name: delay execution if manually executed
        env:
          input_delay: ${{ github.event.inputs.delay_seconds }}
        run: |
          delay=`echo "$input_delay"`
          sleep $delay
        if: ${{ github.event_name == 'workflow_dispatch' }}

      - name: Run a one-line script
        run: echo 'done'
