name: Wait using check-regexp
on:
  pull_request:
    types: [opened, synchronize]
  push:
    tags:
      - 'test-using-regexp/v*' # e.g. test-using-regexp/v1_2_3
  workflow_dispatch:

jobs:
  waited_task_n2:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo 'done'
  unwaited_task_n2:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo 'done'

  wait-for-check-regexp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Wait on tests
        uses: ./
        with:
          ref: ${{ github.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10 # seconds
          running-workflow-name: wait-for-check-regexp
          check-regexp: \Awaited_.?

      - name: Delete tag
        run: git push --delete origin ${{ github.ref }}
        if: ${{ contains(github.ref, 'test-using-regexp') }}

      - name: Success
        run: echo 'success!'
